#! /usr/bin/env bash
#
# Translation provided by Google
# https://www.google.com/

cat << EOF > symbol_map.txt
  # AbstractList -> LystAbstractía

  AbstractList -> ListaDeResúmenes

  constant -> constante
  const -> const
  function -> funcíon
  this -> esta (feminine)
  this -> esto (masculine)
  assert -> afirmar
  return -> devolver
  list -> lista
  a -> una (feminine)
  a -> uno (masculine)
  1 -> uno
  2 -> dos
  value -> valor
  it -> él
  for -> para

  line -> línea
  vector -> vector
  require -> requerir
  3 -> tres
  column -> columna
  new -> nueva (feminine)
  new -> nuevo (masculine)
  feminine -> feminina (feminina)
  feminine -> feminino (masculine)
  masculine -> masculina (feminina)
  masculine -> masculino (masculino)
  type -> tipo
  if -> si
  equal -> igual
  let -> dejar
  fn -> fn
  make -> hacer

  b -> b
  result -> resultado
  o -> oh
  deep equal -> profundo igul
  the -> la (feminina)
  the -> el (masculino)
  to string -> encodar
  describe -> describir
  token -> simbólica (feminina)
  token -> simbólico (masculino)
  console -> consola
  binding -> vinculante
  push -> empujar
  x -> incógnita
  log -> registro
  symbol -> símbolo
  input -> aporte
  error -> error
  s -> s
  parse -> analizar gramaticalmente
  tokenizer -> tokenizador
  true -> veradadera (feminina)
  true -> veradadero (masculino)

  peek -> ojeada
  assert eval to -> afirmar evaluación a
  get -> conseguir
  case -> caso
  pop -> estallido
  false -> falsa (feminina)
  false -> falso (masculino)
  bnd -> bnd
  key -> llave
  to -> a
  of -> de
  c -> do
  eval -> evaluar
  params -> parámetros
  src -> src
  puts -> pone
  0 -> cero
  undefined -> indefinida (feminina)
  undefined -> indefinido (masculino)
  head -> cabeza
  is -> es
  expected -> esperada (feminina)
  expected -> esperado (masculino)
  root binding -> enlace de raíz
  is empty -> esta vacía (feminina)
  is empty -> esta vacío (masculino)
  and -> y
  name -> nombre
  class -> clase

EOF


# alias 😺=cat
# 😺 < symbol_map.txt
cat < symbol_map.txt

