#! /usr/bin/env bash
#
# Translation provided by Google
# https://www.google.com/

cat << EOF > symbol_map.txt
  # AbstractList -> LystAbstractía

  AbstractList -> ListaDeResúmenes

  constant -> constante
  const -> const
  function -> funcíon
  this -> esta (feminine)
  this -> esto (masculine)
  assert -> afirmar
  return -> devolver
  list -> lista
  a -> una (feminine)
  a -> uno (masculine)
  1 -> uno
  2 -> dos
  value -> valor
  it -> él
  for -> para

  line -> línea
  vector -> vector
  require -> requerir
  3 -> tres
  column -> columna
  new -> nueva (feminine)
  new -> nuevo (masculine)
  feminine -> feminina (feminina)
  feminine -> feminino (masculine)
  masculine -> masculina (feminina)
  masculine -> masculino (masculino)
  type -> tipo
  if -> si
  equal -> igual
  let -> dejar
  fn -> fn
  make -> hacer
EOF


cat < symbol_map.txt

