#! /usr/bin/env bash

function enumerarTodosLosFichas() {
  # grep -oP '\w+' $1
  # grep -oP '\w+' $1 | sort | uniq | wc -l
  grep -oP '\w+' $1 | sort | uniq | cat -n
  # grep -oP '\w+' $1 | sort | uniq -c
  # grep -oP '\w+' $1 | sort | uniq -c | sort
}

enumerarTodosLosFichas "$1"
