#! /usr/bin/env bash

# alias eco=echo

declare -A mapaDeSimbolos=(
  ["this"]="esta"
  # ["this"]="esto"
  ["return"]="devolver"
  ["if"]="si"

  # ["a"]="a"
  # ["o"]="o"
  # ["oo"]="oo"
  # ["fn"]="fn"

  ["AbstractList"]="ListaAbstracta"

  ["pop"]="estallido"
  ["get"]="consiguir"
  ["init"]="inicio"
  ["peek"]="ojeada"
  ["find"]="encontrar"
  ["count"]="contar"
  ["value"]="valor"
  ["reduce"]="reducir"
  ["events"]="eventos"
  ["isEmpty"]="estaVacio"

  ["evalExpression"]="evaluarLaExpresión"
  # ["evalExpression"]="expresiónDeEvaluación"
  ["constructor"]="constructora"
  # ["constructor"]="constructoro"
  ["sub"]="sus"
  ["result"]="resultados"
  ["push"]="empujar"
  ["let"]="dejar"
  ["the"]="la"
  # ["the"]="el"
  ["memo"]="memo"
  # ["memorandum"]="memorándum"
  ["make"]="hacer"
  ["else"]="demás"
  ["currentElement"]="elementoActual"
  ["list"]="lista"
  ["head"]="cabeza"
  ["currentNode"]="nodoActual"
  ["array"]="formación"
  ["tail"]="cola"
  ["skip"]="saltar"
  ["prototype"]="prototipo"
  # ["n"]=""
  ["map"]="mapa"
  ["binding"]="vinculante"
  ["and"]="y"
  ["accumulator"]="acumulador"
  # ["ëval"]=""
  ["until"]="hasta"
  ["to"]="a"
  ["take"]="llevar"
  ["is"]="es"
  ["invert"]="invertir"
  ["include"]="incluir"
  ["each"]="cada"
  # ["const"]="const"
  ["class"]="clase"
  # ["bubls"]="bubls"
  ["which"]="cual"
  # ["undefined"]=""
  # ["toStringFormat"]=""
  # ["thisArg"]=""
  ["split"]="dividir"
  # ["sourceList"]=""
  ["partition"]="repartirPara"
  ["null"]="nula"
  # ["null"]="nulo"
  ["new"]="nueva"
  # ["new"]="nuevo"
  # ["mapFn"]=""
  ["last"]="última"
  # ["last"]="último"
  # ["into"]=""
  # ["includes"]=""
  # ["i"]=""
  ["function"]="función"
  # ["from"]=""
  ["for"]="para"
  ["case"]="caso"
  # ["bind"]=""
  # ["be"]=""
  # ["arrayLike"]=""
  # ["Vector"]=""
  # ["Symbol"]=""
  # ["List"]=""
  # ["yield"]=""
  # ["will"]=""
  # ["while"]=""
  # ["what"]=""
  # ["up"]=""
  # ["typeof"]=""
  # ["toStringJoin"]=""
  # ["toString"]=""
  # ["toArray"]=""
  # ["time"]=""
  # ["that"]=""
  # ["symbol"]=""
  # ["switch"]=""
  # ["string"]=""
  # ["static"]=""
  # ["skim"]=""
  # ["shift"]=""
  # ["shared"]=""
  # ["serving"]=""
  # ["serve"]=""
  # ["s"]=""
  # ["returns"]=""
  # ["rest"]=""
  # ["require"]=""
  # ["purposes"]=""
  # ["plop"]=""
  # ["otherwise"]=""
  # ["or"]=""
  # ["on"]=""
  # ["next"]=""
  # ["my"]=""
  # ["more"]=""
  # ["module"]=""
  # ["might"]=""
  # ["method"]=""
  # ["mapEval"]=""
  # ["manipulated"]=""
  # ["locals"]=""
  # ["little"]=""
  # ["keyFor"]=""
  # ["just"]=""
  # ["iterator"]=""
  # ["init"]=""
  # ["here"]=""
  # ["functionality"]=""
  # ["first"]=""
  # ["false"]=""
  # ["exports"]=""
  # ["evalEach"]=""
  # ["empty"]=""
  # ["do"]=""
  # ["destructed"]=""
  # ["define"]=""
  # ["default"]=""
  # ["conventenal"]=""
  # ["conj"]=""
  # ["centralized"]=""
  # ["can"]=""
  # ["but"]=""
  # ["broken"]=""
  # ["between"]=""
  # ["begin"]=""
  # ["base"]=""
  # ["as"]=""
  # ["abstract"]=""

  # ["_toString"]=""
  # ["Use"]=""
  # ["There"]=""
  # ["Simple"]=""
  # ["LongLivePlop"]=""
  # ["Let"]=""
  # ["Array"]=""
  # ["All"]=""
  # ["Aliases"]=""
  # ["0"]=""
)


function buscar_y_reemplazar_símbolo() {
  # echo "$1" ":" "$2" "->" "$3"

    # archivo="$1"
    # simbolo="$2"
  # reemplazo="$3"

  # echo "$archivo" ":" "$simbolo" "->" "$reemplazo"

  # Loop through the file line by line
  while IFS= read -r linea; do
    # echo "$linea"
    # Extrae las palabras de esta línea y
    # colócalas en una matriz.
    # Extract the words for this line and put them
    # into an array
    palabras=($(grep -oP '\w+' <<< "$linea"))
    # echo "${palabras[*]}"

    # # Extrae las palabras no literales de esta
    # # línea y colócalas en una matriz.
    # # Extract the non-words for this line and put
    # # them into an array
    # sin_palabras=($(grep -oP '\W+' <<< "$linea"))
    # sin_palabras=($(grep -oP '\W+' <<< "$linea"))
    # https://stackoverflow.com/a/32931403/30654127
    mapfile -t sin_palabras < <(grep -oP '\W+' <<< "$linea")
    # grep -oP '\W+' <<< "$linea"
    # echo "${sin_palabras[*]}"

    # # Buscar y reemplazar tokens
    # # Find and replace tokens.
    for i in "${!palabras[@]}"; do
      for s in "${!mapaDeSimbolos[@]}"; do
        if [[ "${palabras[i]}" == "$s" ]]; then
          palabras[i]="${mapaDeSimbolos[$s]}"
        fi
      done
    done

    # echo "${palabras[*]}"

    # Reconstruir la linea.
    # Reconstruct the line.
    nueva_linea=""

    # echo "$linea"
    if [[ "$linea" =~ ^[a-zA-Z] ]]; then
      # Line started with word characters
      # zip "$paralbras" "$sin_paralabras"
      # echo "palabras"

      for i in "${!palabras[@]}"; do
          nueva_linea+="${palabras[i]}"
          # Append the corresponding non-word token
          # if it exists
          if [[ -n "${sin_palabras[i]}" ]]; then
              nueva_linea+="${sin_palabras[i]}"
          fi
      done

      # Manejar el token final que no es una
      # palabra si existe
      # Handle the trailing non-word token if it
      # exists
      if [[ "${#palabras[@]}" -lt "${#sin_palabras[@]}" ]]; then
          nueva_linea+="${sin_palabras[-1]}"
      fi

    else
      # Line started with non-word characters
      # echo "sin palabras"
      for i in "${!sin_palabras[@]}"; do
          nueva_linea+="${sin_palabras[i]}"
          # Append the corresponding word token
          # if it exists
          if [[ -n "${palabras[i]}" ]]; then
              nueva_linea+="${palabras[i]}"
          fi
      done

      # Manejar el token de palabra final si
      # existe
      # Handle the trailing word token if it
      # exists
      if [[ "${#sin_palabras[@]}" -lt "${#palabras[@]}" ]]; then
          nueva_linea+="${palabras[-1]}"
      fi
    fi

    echo "$nueva_linea"
    # salida


    # for i in "${!palabras[@]}"; do
    #     nueva_linea+="${palabras[i]}"
    #     # Append the corresponding non-word token
    #     # if it exists
    #     if [[ -n "${sin_palabras[i]}" ]]; then
    #         nueva_linea+="${sin_palabras[i]}"
    #     fi
    # done

    # Handle the trailing non-word token if it exists
    # if [[ "${#words[@]}" -lt "${#non_words[@]}" ]]; then
    #     reconstructed_line+="${non_words[-1]}"
    # fi

    # echo "$reconstructed_line"

  # done < "$archivo"
  done

}

cat "./src/en/abstract_list.js" | \
  # head -n20 | \
  buscar_y_reemplazar_símbolo


# cat "./src/abstract_list.js" | \
#   head -n5

# buscar_y_reemplazar_símbolo \
#   "./src/abstract_list.js" \
#   "AbstractList" \
#   "ListaAbstracta"

# cat "./src/abstract_list.js" | \
#   head -n5 | \
#   buscar_y_reemplazar_símbolo \
#     "" \
#     "AbstractList" \
#     "ListaAbstracta"

# cat "./src/abstract_list.js" | \
#   head -n5 | \
#   buscar_y_reemplazar_símbolo \
#     "" \
#     "function" \
#     "función"

# cat "./src/abstract_list.js" | \
#   # head -n20 | \
#   buscar_y_reemplazar_símbolo \
#     "" \
#     "AbstractList" \
#     "ListaAbstracta"

exit

# TODO: Dry run option
# TODO implement limit to xirectory
# TODO: Check for issues, files that already exist, warn
# TODo: Add directories to ignore option.
# TODO: Needs to renames symbol tokens, not
# partial tokens, so Bubble -> Quote shouldn't
# change BubbleScript, match symbol delimiters on
# the outside of symbol being rename (){}[] \nEOT"

# rename original nuevo [dir]

function camelizar() {
  echo $1 | sed -E 's/_([a-z])/\U\1/g' | sed -E 's/^(.)/\L\1/'
}

function pascalizar() {
  echo $1 | sed -E 's/_([a-z])/\U\1/g' | sed -E 's/^(.)/\U\1/'
}

function subrayar() {
  echo $1 | sed -E 's/([A-Z])/_\L\1/g' | sed -E 's/^_//'
}

function rebautizar() {
  git grep -l $1 | xargs sed -i -e "s/$1/$2/g"

  # File renaming.
  files=$(git ls-tree --full-tree --name-only -r HEAD)
  # Filter file list by orginal text
  files=$(echo "$files" | grep "$1")

  # IFS=$"\n"
  # for file in "${files[@]}"; do
  for file in $files; do
    echo "Renaming: $file"
    # get new path
    new_path=$(echo "$file" | sed "s/$1/$2/g")
    # new_path=$(echo "$file" | sed "s/([ ()\[\]{}])$1(/\1$2/g")
    echo "$new_path"
    # get dir
    directory_path=$(dirname "$new_path")
    mkdir -p "$directory_name"
    # rename old to new
    mv "$file" "$new_path"
  done
  # IFS=$" \t\n"e
}

rebautizar "$(camelizar $1)" "$(camelizar $2)"
rebautizar "$(pascalizar $1)" "$(pascalizar $2)"
rebautizar "$(subrayar $1)" "$(subrayar $2)"
exit


camelloVieja="$(camelizar \"$1\")"
camelloNuevo="$(camelizar \"$2\")"

# orginal_texto = $1;
# nuevo_texto
# echo $1 $2
# git grep -l $1 | xargs sed -i -e "s/$1/$2/g"

# File renaming.
files=$(git ls-tree --full-tree --name-only -r HEAD)
# Filter file list by orginal text
files=$(echo "$files" | grep "$1")

# IFS=$"\n"
# for file in "${files[@]}"; do
for file in $files; do
  echo "Renaming: $file"
  # get new path
  new_path=$(echo "$file" | sed "s/$1/$2/g")
  echo "$new_path"
  # get dir
  # directory_path=$(dirname "$new_path")
  # mkdir -p "$directory_name"
  # rename old to new
  # mv "$file" "$new_path"
done
# IFS=$" \t\n"e
