#! /usr/bin/node bin/bubls
(muf puts
  (fn [msg]
    (console.log msg)))
(puts "Hello Sunshine!")
(puts 1234)
(puts (+ 12 34))
(puts "hiya")

(let [a 5]
  (console.log (+ a a))
  (console.log (+ a a a)))
