#! /usr/bin/env bash

# TODO: Dry run option
# TODO implement limit to xirectory
# TODO: Check for issues, files that already exist, warn
# TODo: Add directories to ignore option.
# TODO: Needs to renames symbol tokens, not
# partial tokens, so Bubble -> Quote shouldn't
# change BubbleScript, match symbol delimiters on
# the outside of symbol being rename (){}[] \nEOT"

# rename original nuevo [dir]

function camelizar() {
  echo $1 | sed -E 's/_([a-z])/\U\1/g' | sed -E 's/^(.)/\L\1/'
}

function pascalizar() {
  echo $1 | sed -E 's/_([a-z])/\U\1/g' | sed -E 's/^(.)/\U\1/'
}

function subrayar() {
  echo $1 | sed -E 's/([A-Z])/_\L\1/g' | sed -E 's/^_//'
}

function rebautizar() {
  git grep -l $1 src test lib bin script | xargs \
    sed -i -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
           -e "s/^$1\(\W\)/$2\1/g" \
           -e "s/\(\W\)$1$/\1$2/g" \
           -e "s/^$1$/$2/g"
}

function rebautizar_archivos() {
  # File renaming.
  files=$(git ls-tree --full-tree --name-only -r HEAD src test lib script bin)
  # Filter file list by orginal text
  files=$(echo "$files" | grep "$1")

  # IFS=$"\n"
  # for file in "${files[@]}"; do
  for file in $files; do
    echo "Renaming: $file"
    # get new path
    # new_path=$(echo "$file" | sed "s/$1/$2/g")
    new_path=$(echo "$file" | \
      sed -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
          -e "s/^$1\(\W\)/$2\1/g" \
          -e "s/\(\W\)$1$/\1$2/g" \
          -e "s/^$1$/$2/g")

    echo "$new_path"
    # get dir
    directory_path=$(dirname "$new_path")
    mkdir -p "$directory_name"
    # rename old to new
    mv "$file" "$new_path"
  done
  # IFS=$" \t\n"e
}

rebautizar "$(camelizar $1)" "$(camelizar $2)"
rebautizar "$(pascalizar $1)" "$(pascalizar $2)"
rebautizar "$(subrayar $1)" "$(subrayar $2)"

rebautizar_archivos "$(camelizar $1)" "$(camelizar $2)"
rebautizar_archivos "$(pascalizar $1)" "$(pascalizar $2)"
rebautizar_archivos "$(subrayar $1)" "$(subrayar $2)"
exit


camelloVieja="$(camelizar \"$1\")"
camelloNuevo="$(camelizar \"$2\")"

# orginal_texto = $1;
# nuevo_texto
# echo $1 $2
# git grep -l $1 | xargs sed -i -e "s/$1/$2/g"

# File renaming.
files=$(git ls-tree --full-tree --name-only -r HEAD)
# Filter file list by orginal text
files=$(echo "$files" | grep "$1")

# IFS=$"\n"
# for file in "${files[@]}"; do
for file in $files; do
  echo "Renaming: $file"
  # get new path
  new_path=$(echo "$file" | sed "s/$1/$2/g")
  echo "$new_path"
  # get dir
  # directory_path=$(dirname "$new_path")
  # mkdir -p "$directory_name"
  # rename old to new
  # mv "$file" "$new_path"
done
# IFS=$" \t\n"e
