#! /usr/bin/env bash

# Does a project wide symbol rename.
# script/🍄 original nuevo [dirs]

# TODO: Dry run option
# TODO: Check for issues, files that already exist,
# warn
# TODO: Address warning and errors being printed.
# TODO: sed desnt seem to work on files with ö in the
# name. Maybe update? Work around if neccesary...
# TODO: Can't decern wheter to use camel case or
# underscore when going from single to multiple
# portion symbol, for example list ->
# bubbleButt|bubble_butt. For this, it seems context
# is required.


function camelizar() {
  echo $1 | sed -E 's/_([a-z])/\U\1/g' | sed -E 's/^(.)/\L\1/'
}

function pascalizar() {
  echo $1 | sed -E 's/_([a-z])/\U\1/g' | sed -E 's/^(.)/\U\1/'
}

function subrayar() {
  echo $1 | sed -E 's/([A-Z])/_\L\1/g' | sed -E 's/^_//'
}

function rebautizar() {
  durs=$(echo $@ | cut -d' ' -f3-)

  git grep -l $1 $durs | xargs \
    sed -i -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
           -e "s/^$1\(\W\)/$2\1/g" \
           -e "s/\(\W\)$1$/\1$2/g" \
           -e "s/^$1$/$2/g"
}

function rebautizar_archivos() {
  durs=$(echo $@ | cut -d' ' -f3-)

  # File renaming.
  files=$(git ls-tree --full-tree --name-only -r HEAD $durs)
  # Filter file list by orginal text
  files=$(echo "$files" | grep "$1")

  # IFS=$"\n"
  # for file in "${files[@]}"; do
  for file in $files; do
    echo "Renaming: $file"
    # get new path
    # new_path=$(echo "$file" | sed "s/$1/$2/g")
    new_path=$(echo "$file" | \
      sed -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
          -e "s/^$1\(\W\)/$2\1/g" \
          -e "s/\(\W\)$1$/\1$2/g" \
          -e "s/^$1$/$2/g")

    echo "$new_path"
    # get dir
    directory_path=$(dirname "$new_path")
    mkdir -p "$directory_name"
    # rename old to new
    mv "$file" "$new_path"
  done
  # IFS=$" \t\n"e
}

durs=$(echo $@ | cut -d' ' -f3-)

rebautizar "$(subrayar \"\\/$1\")" "$(subrayar \"\\/$2\")" $durs
rebautizar "$(camelizar $1)" "$(camelizar $2)" $durs
rebautizar "$(pascalizar $1)" "$(pascalizar $2)" $durs
rebautizar "$(subrayar $1)" "$(subrayar $2)" $durs

rebautizar_archivos "$(subrayar $1)" "$(subrayar $2)" $durs
# rebautizar_archivos "$(camelizar $1)" "$(camelizar $2)" $durs
# rebautizar_archivos "$(pascalizar $1)" "$(pascalizar $2)" $durs
