#! /usr/bin/env bash

# Symbol Renamer
#
#    $ script/🍉 inicial nuevo [durs]

durs=$(echo $@ | cut -d' ' -f3-)

files=$(git grep -l $1 $durs)

files=$(echo "$files" | \
        sed -E 's/^["'\''"]|["'\''"]$//g')

files=$(printf "%b\n" "$files")

echo "$files" | xargs \
  sed -i -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
         -e "s/^$1\(\W\)/$2\1/g" \
         -e "s/\(\W\)$1$/\1$2/g" \
         -e "s/^$1$/$2/g"


