#! /usr/bin/env bash

# File name symbol renamer
# script/🍄 original nuevo [dirs]

durs=$(echo $@ | cut -d' ' -f3-)

# File renaming.
files=$(git ls-tree --full-tree --name-only -r HEAD $durs)
# Filter file list by orginal text
# files=$(echo "$files" | grep "^$1\W$1")
files=$(echo "$files" | \
          grep -e "\W$1\W" -e "^$1\W" \
               -e "\W$1$"  -e "^$1$")


# echo "$files"

# # for file in "${files[@]}"; do
for file in $files; do
  echo "Renaming: $file"
  # get new path
  # new_path=$(echo "$file" | sed "s/$1/$2/g")
  new_path=$(echo "$file" | \
    sed -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
        -e "s/^$1\(\W\)/$2\1/g" \
        -e "s/\(\W\)$1$/\1$2/g" \
        -e "s/^$1$/$2/g")

  echo "$new_path"
  # get dir
  directory_path=$(dirname "$new_path")
  echo mkdir -p "$directory_path"
  # rename old to new
  echo mv "$file" "$new_path"
done
