#! /usr/bin/env bash

# File name symbol renamer
# script/🍋 original nuevo [dirs]

# TODO: Add checking to make sure files aren't overwritten. Would be nice to check this up front, and abort if there are any name conflicts detected, cobsidering this command can rename mire than file
# TODO: Does not currently work with emoji, need to figure oyt how to pricess the unicode, which i think is being returned raw for ls-tree, this may also remive the need to strip the escaped ""

durs=$(echo $@ | cut -d' ' -f3-)

# File renaming.
files=$(git ls-tree --full-tree --name-only -r HEAD $durs)
# Filter file list by orginal text
# files=$(echo "$files" | grep "^$1\W$1")
files=$(echo "$files" | \
          grep -e "\W$1\W" -e "^$1\W" \
               -e "\W$1$"  -e "^$1$")

# Remove wrapping double quotes that might be
# included with certian files because of special
# characters.
files=$(echo "$files" | \
        sed -E 's/^["'\''"]|["'\''"]$//g')

# This seems to work for parsing the octal encoded unicode
files=$(printf "%b\n" "$files")
# echo "$files"

# echo $"$files"
# for file in $files; do
#   # echo $(echo "$'$file'")
#   printf "%b\n" "$file"
# done

for file in $files; do
  # get new path
  # new_path=$(echo "$file" | sed "s/$1/$2/g")
  new_path=$(echo "$file" | \
    sed -e "s/\(\W\)$1\(\W\)/\1$2\2/g" \
        -e "s/^$1\(\W\)/$2\1/g" \
        -e "s/\(\W\)$1$/\1$2/g" \
        -e "s/^$1$/$2/g")

  # echo new_path $new_path

  # Ensure the move to directory exists
  _dir=$(dirname $new_path)
  # echo _dir "$_dir"
  if [ ! -d "$_dir" ]; then
    echo "Create directory: $_dir"
    echo mkdir -p "$_dir"
  fi

  echo "Renaming: $file => $new_path"
  # rename old to new
  mv "$file" "$new_path"
done
